version: "3.8"

services:
  frontend:
    build:
      context: E:\devops-with-docker\material-applications\example-frontend
    ports:
      - 5000:5000
    environment:
      - REACT_APP_BACKEND_URL=http://localhost/api/
    container_name: frontend-compose

  backend:
    build:
      context: E:\devops-with-docker\material-applications\example-backend
    ports:
      - 8080:8080
    environment:
      - REQUEST_ORIGIN=http://localhost/
      - REDIS_HOST=redis
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_HOST=db
      - POSTGRES_DATABASE=postgres
    container_name: backend-compose

  redis:
    image: redis
    ports:
      - 6379:6379
    container_name: redis-compose
    restart: unless-stopped

  db:
    image: postgres:13.2-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
    container_name: db_redmine
    volumes:
      - .\database:/var/lib/postgresql/data

  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - .\nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    container_name: nginx
