version: '3.8'

services:
  frontend:
    build: 
      context: D:\Docker\devops-with-docker\material-applications\example-frontend
    ports: 
      - 5000:5000
    container_name: frontend

  backend:
    build:
      context: D:\Docker\devops-with-docker\material-applications\example-backend
    ports: 
      - 8080:8080
    container_name: backend