version: "3.8"

services:
  frontend:
    build:
      context: E:\devops-with-docker\material-applications\example-frontend
    ports:
      - 5000:5000
    container_name: frontend

  backend:
    build:
      context: E:\devops-with-docker\material-applications\example-backend
    ports:
      - 8080:8080
    container_name: backend

  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - .\nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    container_name: nginx
